FoodPlanner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from FoodPlanner import settings
import django.views.static as static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^food/', include('food.urls', app_name='food', namespace='food')),
    url(r'^person/', include('person.urls', app_name='person', namespace='person')),
    url(r'^diet/', include('diet.urls', app_name='diet', namespace='diet')),
    url(r'^searcher/', include('searcher.urls', app_name='searcher', namespace='searcher')),
    url(r'^crawler/', include('crawler.urls', app_name='crawler', namespace='crawler')),
    url(r'^$', TemplateView.as_view(template_name='main.html')),

]

api/urls.py
from django.conf.urls import url, include

from rest_framework import routers
from rest_framework.authtoken import views

from api.views import DishViewSet


router = routers.DefaultRouter()
router.register(r'dishes', DishViewSet, 'dishes')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-token-auth/', views.obtain_auth_token),
]

diet/urls.py
from django.conf.urls import url
import diet.views as v

urlpatterns = [
    url(r'^$', v.DietsView.as_view(), name='diets'),
    url(r'^(?P<pk>[0-9]+)/$', v.DietDetail.as_view(), name='diet'),
]

diet/models.py
import random
from typing import List

from collections import defaultdict
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.core.exceptions import ValidationError
from markdownx.models import MarkdownxField

import food.models as f
from diet.utils import meals, convert_to_grams


class Diet(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=256)
    description = MarkdownxField(null=True, blank=True)
    dishes = models.ManyToManyField(f.Dish, related_name='diets')
    number_of_meals = models.IntegerField(default=4)
    number_of_weeks = models.IntegerField(null=True, blank=True)
    number_of_days = models.IntegerField(null=True, blank=True)
    # {day!int: mapOf(meal to dish)}
    days = JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        if not self.number_of_weeks and not self.number_of_days:
            raise ValidationError('You have to set either number of weeks or number of days')
        elif self.number_of_weeks and self.number_of_days:
            raise ValidationError('You have to set only number of weeks or number of days')

    def generate(self):
        self.days = self.days_to_dishes()

    def days_to_dishes(self) -> List[List[int]]:
        dishes = [self.get_dishes_for_meal(meal) for meal in meals(self.number_of_meals)]

        return [self.one_day_dishes(dishes) for _ in self.total_days]

    @property
    def total_days(self):
        total_days = self.number_of_days if self.number_of_days else self.number_of_weeks * 7
        return range(1, total_days + 1)

    @staticmethod
    def one_day_dishes(dishes: List[List['f.Dish']]) -> List[int]:
        result = []
        for meal_dishes in dishes:
            random.shuffle(meal_dishes)
            for dish in meal_dishes:
                if dish.pk not in result:
                    result.append(dish.pk)
                    break

        if len(result) < len(dishes):
            candidates = [d.pk for meal_dishes in dishes for d in meal_dishes if d.pk not in result]
            if not candidates:
                candidates = list(result)
            random.shuffle(candidates)

            result += [candidates[i % len(candidates)] for i in range(len(dishes) - len(result))]

        return result

    def get_dishes_for_meal(self, meal):
        return list(self.dishes.filter(meals__title=meal).distinct())

    def day_dishes(self, from_day=0, to_day=None):
        if not to_day:
            to_day = len(self.days)

        if from_day > to_day:
            return []
        return [[self.dishes.filter(pk=pk).first() for pk in day] for day in self.days[from_day: to_day]]

    def ingredients_for_period(self, from_day=0, to_day=None):
        dishes = sum(self.day_dishes(from_day=from_day, to_day=to_day), [])
        ingredients = defaultdict(list)
        for dish in dishes:
            ingredient_to_amount = dish.ingredient_to_amount()
            for ingredient, amount in ingredient_to_amount.items():
                ingredients[ingredient].append(amount)

        result = {}
        for ingredient, amounts in ingredients.items():
            total_g = sum(convert_to_grams(ingredient, amount['amount'], amount['unit']) for amount in amounts)
            result[ingredient] = total_g, f.Unit.GR

        return result

    def counted_dishes(self, from_day=0, to_day=None):
        dishes = sum(self.day_dishes(from_day=from_day, to_day=to_day), [])
        result = defaultdict(int)
        for d in dishes:
            result[d] += 1
        return result.items()

diet/views.py
from django.views.generic import ListView, DetailView

from diet.models import Diet


class DietsView(ListView):
    model = Diet
    template_name = 'diet_list.html'


class DietDetail(DetailView):
    model = Diet
    template_name = 'diet_detail.html'

diet/templates/diet_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block page_style %}
{% endblock %}

{% block content %}
<h1>{{ object.title|capfirst }}</h1>
<div class="mb-1">
    {{ object.description}}
</div>

<table>
    <tr>
        <th>{% trans "Number of meals" %}</th>
        <td>{{ object.number_of_meals }}</td>
    </tr>
    {% if object.number_of_days %}
    <tr>
        <th>{% trans "Number of days" %}</th>
        <td>{{ object.number_of_days }}</td>
    </tr>
    {% else %}
    <tr>
        <th>{% trans "Number of weeks" %}</th>
        <td>{{ object.number_of_weeks }}</td>
    </tr>
    {% endif %}
</table>

<h2>{% trans "Dishes" %}</h2>
<table class="table">
    <tr>
        <th>{% trans "Dish" %}</th>
        <th>{% trans "Appear times" %}</th>
    </tr>
    {% for dish, times in object.counted_dishes %}
    <tr>
        <th>{{ dish }}</th>
        <td>{{ times }}</td>
    </tr>
    {% endfor %}
</table>

<h2>{% trans "Menu" %}</h2>
<table class="table">
    <tr class="header">
        <th>{% trans "Day" %}</th>
        <th>{% trans "Dishes" %}</th>
    </tr>
    {% for day in object.day_dishes %}
    <tr>
        <td rowspan="{{ object.number_of_meals|add:1 }}">{{ forloop.counter }}</td>
    </tr>
    {% for dish in day %}
    <tr>
        <td>{{ dish }}</td>
    </tr>
    {% endfor %}
    {% endfor %}
</table>

<h2>{% trans "Ingredients" %}</h2>
<table class="table table-compact">
    {% for ingredient, amount in object.ingredients_for_period.items %}
    <tr>
        <td>{{ ingredient }}</td>
        <td>{{ amount.0 }} {{ amount.1 }}</td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

diet/templates/diet_list.html
{% extends 'base.html' %}
{% block content %}
<ul>
    {% for diet in object_list %}
    <li><a href="{% url 'diet:diet' diet.pk %}">{{ diet.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}