FoodPlanner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from FoodPlanner import settings
import django.views.static as static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^food/', include('food.urls', app_name='food', namespace='food')),
    url(r'^person/', include('person.urls', app_name='person', namespace='person')),
    url(r'^diet/', include('diet.urls', app_name='diet', namespace='diet')),
    url(r'^searcher/', include('searcher.urls', app_name='searcher', namespace='searcher')),
    url(r'^crawler/', include('crawler.urls', app_name='crawler', namespace='crawler')),
    url(r'^$', TemplateView.as_view(template_name='main.html')),

]

api/urls.py
from django.conf.urls import url, include

from rest_framework import routers
from rest_framework.authtoken import views

from api.views import DishViewSet


router = routers.DefaultRouter()
router.register(r'dishes', DishViewSet, 'dishes')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-token-auth/', views.obtain_auth_token),
]

diet/urls.py
from django.conf.urls import url
import diet.views as v

urlpatterns = [
    url(r'^$', v.DietsView.as_view(), name='diets'),
    url(r'^(?P<pk>[0-9]+)/$', v.DietDetail.as_view(), name='diet'),
]

food/urls.py
from django.conf.urls import url
import food.views as f


urlpatterns = [
    url(r'^dishes$', f.DishesView.as_view(), name='dishes'),
    url(r'^dishes/(?P<pk>\d+)$', f.DishView.as_view(), name='dish'),
    url(r'^dishes/editing/(?P<pk>\d+)?$', f.DishCreate.as_view(), name='editing'),
    url(r'^ingredients/$', f.IngredientsView.as_view(), name='ingredients'),
]

searcher/urls.py
from django.conf.urls import url
import searcher.views as s

urlpatterns = [
    url(r'^$', s.SearcherView.as_view(), name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Food planer{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
            integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    {% block page_style %}{% endblock %}
</head>
<body>
{% include "navabar.html" %}
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/main.html
{% extends 'base.html' %}
{% block content %}
<ul>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
    <li><a href="{% url 'food:dishes' %}">Dishes</a></li>
    <li><a href="{% url 'api:api-root' %}">Api Root</a></li>
    <li><a href="{% url 'diet:diets' %}">Diets</a></li>
</ul>
{% endblock %}

templates/navabar.html
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Chef</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
            <li class="nav-item active"><a href="{% url 'api:api-root' %}" class="nav-link">Api Root</a></li>
            <li class="nav-item active"></li>
            <li class="nav-item active"><a href="{% url 'diet:diets' %}" class="nav-link">Diets</a></li>
            <li class="nav-item active"><a href="{% url 'crawler:crawler' %}" class="nav-link">Crawler</a></li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false">Dishes</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'food:dishes' %}">All dishes</a>
                    <a class="dropdown-item" href="{% url 'food:editing' %}">Create</a>
                    <a class="dropdown-item" href="{% url 'food:ingredients' %}">Upload ingredients</a>
                </div>
            </li>
        </ul>


        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'searcher:search' %}">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="query" value="{{ query }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>